#
# Makefile for linux/drivers/platform
#
CFLAGS_KERNEL := -fno-unsafe-math-optimizations -fno-strict-aliasing

obj-$(CONFIG_X86)		+= x86/
obj-$(CONFIG_OLPC)		+= olpc/
obj-$(CONFIG_GOLDFISH)		+= goldfish/
obj-$(CONFIG_ARCH_MSM)		+= msm/
