#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_FPC1020_HYDROGEN)	+= fpc1020_hydrogen/
obj-$(CONFIG_FINGERPRINT_FPC1020_KENZO)	+= fpc1020_kenzo/
obj-$(CONFIG_FINGERPRINT_GOODIX_GF318M)	+= goodix/
