#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_FPC1020)	+= fpc1020/
obj-$(CONFIG_FINGERPRINT_FPC1020_TA)	+= fpc1020_ta/
obj-$(CONFIG_INPUT_FPC1020)		+= fpc1020_tee.o
obj-$(CONFIG_FINGERPRINT_GOODIX_GF318M) += goodix/
