#! /vendor/bin/sh

md5pie="`cat /vendor/agni/wlan_pie.md5`"
md5q="`cat /vendor/agni/wlan_q.md5`"
md5wlan="`md5sum /vendor/agni/wlan.ko`"

echo " 			AGNi Wifi driver switcher utility"
echo " "
echo "   Note: Settings do not persist after reboot. Reinstall from AGNi kernel zip for that."
echo " "
echo " 1: Load Pie based Wifi driver (which is fast & most stable)"
echo " 2: Load Q based Wifi driver (which can be slow)"
echo " 0:   EXIT"
echo " "
echo "        Disable wifi from rom settings before proceeding"
echo " "
echo "Select your choice :"
read -r choice;

if [ $choice -eq 1 ]; then
	rmmod wlan.ko;
	insmod /vendor/agni/wlan_pie.ko && echo "Now, Pie-Based wifi driver is loaded. You can enable wifi from rom settings.";
elif [ $choice -eq 2 ]; then
	rmmod wlan.ko;
	insmod /vendor/agni/wlan_q.ko && echo "Now, Q-Based wifi driver is loaded. You can enable wifi from rom settings.";
elif [ $choice -eq 0 ]; then
	exit;
else
	echo -e " Enter corrent input and try again.";
fi;

